"""
awards.py
=========
Capacity release awards -> bronze.gawd.

No TSP header at the payload level: each award carries its own TSP fields, so
`header_keys` is empty.

Nested `locations` and `rates` are exploded in Silver by stage 3 into
awards_locations / awards_rates. The award-level row keeps them as
JSON text columns; stage 3's decomposition drops those two columns from
awards_core, since the agreed core schema excludes them.
"""

from __future__ import annotations

from .spec import FeedDefinition

FEED = FeedDefinition(
    feed_type="gAWD",
    table="gawd",
    records_keys=("awards", "Awards"),
    parent_id_field="Id",
    parent_required=("Id", "AwardNumber"),
    header_keys=(),
    nested_sections=("locations", "rates"),
    columns=[
        ("GS_ID", "int"),
        ("Id", "varchar"),
        ("TransportationServiceProviderName", "varchar"),
        ("TransportationServiceProviderPropCode", "varchar"),
        ("Status", "varchar"),
        ("StatusCodeValue", "varchar"),
        ("OfferNumber", "varchar"),
        ("BidNumber", "varchar"),
        ("AwardNumber", "varchar"),
        ("AwardQuantityContract", "varchar"),
        ("IBRIndexBasedCapacityReleaseIndicator", "varchar"),
        ("IBRIndexBasedCapacityReleaseIndicatorCodeValue", "varchar"),
        ("RecallReputIndicator", "varchar"),
        ("RecallReputIndicatorCodeValue", "varchar"),
        ("AllowableReleaseIndicator", "varchar"),
        ("AffiliatedIndicator", "varchar"),
        ("AffiliatedIndicatorCodeValue", "varchar"),
        ("RightToAmendPrimaryPointsIndicator", "varchar"),
        ("RightToAmendPrimaryPointsIndicatorCodeValue", "varchar"),
        ("REI_AwardingAction", "varchar"),
        ("REI_StorageInventoryCondition", "varchar"),
        ("CapacityAwardDateTime", "datetime"),
        ("ReleaseTermStartDate", "datetime"),
        ("ReleaseTermEndDate", "datetime"),
        ("PostDateTime", "datetime"),
        ("MarketBasedRateIndicator", "varchar"),
        ("MarketBasedRateIndicatorCodeValue", "varchar"),
        ("PrearrangedDealIndicator", "varchar"),
        ("PrearrangedDealIndicatorCodeValue", "varchar"),
        ("PreviouslyReleasedIndicator", "varchar"),
        ("PreviouslyReleasedIndicatorCodeValue", "varchar"),
        ("PermanentReleaseIndicator", "varchar"),
        ("PermanentReleaseIndicatorCodeValue", "varchar"),
        ("ReplacementShipperRoleIndicator", "varchar"),
        ("ReplacementShipperRoleIndicatorCodeValue", "varchar"),
        ("StorageInventoryConditionedReleaseIndicator", "varchar"),
        ("StorageInventoryConditionedReleaseIndicatorCodeValue", "varchar"),
        ("OverrunResponsibilityIndicator", "varchar"),
        ("OverrunResponsibilityIndicatorCodeValue", "varchar"),
        ("BusinessDayIndicator", "varchar"),
        ("BidderName", "varchar"),
        ("BidderDuns", "int"),
        ("ReleaserName", "varchar"),
        ("ReleaserDuns", "int"),
        ("BidderPhoneNumber", "varchar"),
        ("BidderEmailAddress", "varchar"),
        ("RateFormTypeCode", "varchar"),
        ("RateFormTypeCodeValue", "varchar"),
        ("ReservationRateBasis", "varchar"),
        ("ReservationRateBasisCodeValue", "varchar"),
        ("RateSchedule", "varchar"),
        ("UnitPrice", "varchar"),
        ("Multiplier", "varchar"),
        ("MonetaryAmount", "varchar"),
        ("ReleaseDesignationAcceptableBiddingBasis", "varchar"),
        ("ReleaseDesignationAcceptableBiddingBasisCodeValue", "varchar"),
        ("SurchargeIndicator", "varchar"),
        ("SurchargeIndicatorCodeValue", "varchar"),
        ("ChargeIndicator", "varchar"),
        ("CycleIndicator", "varchar"),
        ("CycleIndicatorCodeValue", "varchar"),
        ("IBRFormulaIdentifier", "varchar"),
        ("IBRFormulaIdentifierCodeValue", "varchar"),
        ("IBRIndexMathematicalOperatorIndicator", "varchar"),
        ("IBRIndexMathematicalOperatorIndicatorCodeValue", "varchar"),
        ("IBRIndexReference1", "varchar"),
        ("IBRIndexReference2", "varchar"),
        ("IBRUniqueFormulaSpecialTerms", "varchar"),
        ("IBRVariableMathematicalOperatorIndicator", "varchar"),
        ("ReplacementShipperContractNumber", "varchar"),
        ("AgencyQualifierCode", "varchar"),
        ("RecallReputTermRate", "varchar"),
        ("RightToAmendPrimaryPointsTermsNote", "varchar"),
        ("SpecialTermsAndMiscellaneousNotesAndObligations", "varchar"),
        ("SpecialTermsAndMiscellaneousNotesStorageInventoryConditions", "varchar"),
        ("SpecialTermsAndMiscellaneousNotes", "varchar"),
        ("MeasurementBasis", "varchar"),
        ("MeasurementBasisCodeValue", "varchar"),
        ("CreatedDate", "datetime"),
        ("ReleaserContractNumber", "varchar"),
        ("ReleaseFullName", "varchar"),
        ("BidderFullName", "varchar"),
        ("Version_Status", "varchar"),
        ("UpdatedDateTime", "datetime"),
        ("locations", "json"),
        ("rates", "json"),
    ],
)
